import os
import re
import shutil
import uuid as uuid_mod
import sqlite3
import json
import tempfile
import hashlib

from core.templates import (
    BASE_DIR, PREFAB_LUA, COSMETIC_LUA, PREFABDATA_LUA,
    LUADATABASE_LUA, TECHTREE_LUA, REBIRTH_TECHTREE_LUA,
    INGEN_DATABASE_LUA, DINOSAUR_MODS_TECHTREE_LUA,
    INIT_DATABASE_LUA, ICON_MOUNT_LUA, ICON_MANAGER_DATABASE_BLOCK,
    MANIFEST_XML,
    SCALE_TEMPLATE, SCALE_TEMPLATE_FALLBACK, SCALE_CONTROLLER_TEMPLATE, SCALE_REQUIRE,
    DEFAULT_SPECIES_STATS, DEFAULT_GENOMES, DEFAULT_SPECIALISATION,
    DEFAULT_EXPEDITIONS, DEFAULT_BUILDING_UPGRADES
)
from core.database import (
    clone_fdb, clone_expeditions_fdb, ensure_table, allocate_species_ids,
    resolve_family_members, add_provenance_view,
)


IDENTIFIER_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")
WINDOWS_RESERVED = {
    "CON", "PRN", "AUX", "NUL", *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}
OWNERSHIP_FILE = ".species_generator_files.json"
LUA_PROVENANCE_COMMENT = "-- Generated by SpeciesGenerator\n"


def _write_generated_lua(path, content):
    """Write generated Lua with a behavior-neutral provenance comment."""
    if not content.startswith(LUA_PROVENANCE_COMMENT):
        content = LUA_PROVENANCE_COMMENT + content
    with open(path, "w", encoding="utf-8") as stream:
        stream.write(content)


def validate_output_identifier(value, label):
    """Validate an identifier used as both Lua symbol and Windows basename."""
    if not isinstance(value, str) or not value:
        raise ValueError(f"{label} is required")
    if value != value.strip() or value.endswith((".", " ")):
        raise ValueError(f"{label} cannot have leading/trailing spaces or dots")
    if os.path.isabs(value) or "/" in value or "\\" in value or ".." in value:
        raise ValueError(f"{label} cannot contain a path, separators, or traversal")
    if not IDENTIFIER_RE.fullmatch(value):
        raise ValueError(
            f"{label} must start with a letter and contain only letters, digits, and underscores")
    if value.split(".", 1)[0].upper() in WINDOWS_RESERVED:
        raise ValueError(f"{label} uses reserved Windows basename {value!r}")
    return value


def _exact_case_output_path(parent, filename):
    """Return an output path and migrate an older case-only spelling."""
    desired = os.path.join(parent, filename)
    if not os.path.isdir(parent):
        return desired
    match = next((entry for entry in os.listdir(parent)
                  if entry.casefold() == filename.casefold()), None)
    if match is None or match == filename:
        return desired
    existing = os.path.join(parent, match)
    temporary = os.path.join(parent, f".{filename}.case-{uuid_mod.uuid4().hex}")
    os.replace(existing, temporary)
    os.replace(temporary, desired)
    return desired


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _assert_tree_safe(root):
    """Reject symlink/junction escapes before copying, writing, or cleanup."""
    if not os.path.exists(root):
        return
    def is_reparse(path):
        attrs = getattr(os.stat(path, follow_symlinks=False), "st_file_attributes", 0)
        return bool(attrs & getattr(__import__("stat"), "FILE_ATTRIBUTE_REPARSE_POINT", 0))
    if os.path.islink(root) or is_reparse(root):
        raise RuntimeError(f"Refusing generated project rooted at a link/reparse point: {root}")
    root_real = os.path.realpath(root)
    for current, dirs, files in os.walk(root):
        for name in dirs + files:
            path = os.path.join(current, name)
            if os.path.islink(path) or is_reparse(path) or os.path.commonpath(
                    [root_real, os.path.realpath(path)]) != root_real:
                raise RuntimeError(f"Refusing generated project containing link/reparse escape: {path}")


def _safe_rmtree(path, parent):
    path_real = os.path.realpath(path)
    parent_real = os.path.realpath(parent)
    if os.path.commonpath([path_real, parent_real]) != parent_real or path_real == parent_real:
        raise RuntimeError(f"Refusing unsafe cleanup outside staging root: {path}")
    if os.path.isdir(path):
        shutil.rmtree(path)


def _invoke_fault(config, stage):
    fault = config.get("_fault_injector")
    if callable(fault):
        fault(stage)


from core.localizations import generate_species_localizations
from core.ppuipkg import (
    normalise_mod_asset_package, read_package, write_package,
)
from core.tex import (png_size, read_tex, write_tex,
                      DEFAULT_TEXEL, DEFAULT_COMPRESSION)


# --- Default (placeholder) icon set -----------------------------------------
#
# Vendored vanilla art the generator can hand a new species so it has SOMETHING
# in every icon slot until the author supplies their own. Harvested by
# `extract_ui_svgs.py`; the PNG pair was copied out of the extracted UI tree.
ICON_TEMPLATE_DIR = os.path.join(BASE_DIR, "templates", "icons")
PLACEHOLDER_SVG = os.path.join(
    ICON_TEMPLATE_DIR, "UIGameface", "img", "icons", "dinosaurSpecies",
    "Allosaurus.svg")
PLACEHOLDER_PNGS = {
    # slot: (template stem, path segment, image-name prefix)
    "small":    ("placeholder_small",    "small",    "dinosaurs_small"),
    "headshot": ("placeholder_headshot", "headshot", "dinosaurs_headshot"),
}


def _default_icon_asset_package(mod_name, slot):
    """Namespaced UI stream whose lowercase spelling keeps STATIC first."""
    return normalise_mod_asset_package(
        mod_name, f"{mod_name}_Dinosaur_{slot.capitalize()}")


def audit_ui_texture_archives(ui_dir):
    """Reject local texture streams that cobra-tools sorts before STATIC.

    This is a pre-pack safety rail for the native LoadOverlay crash diagnosed
    with ArthurianInitiative. PPUIPKG references without a local .tex are not
    checked because they may intentionally target a vanilla/external stream.
    """
    unsafe = []
    if not os.path.isdir(ui_dir):
        return
    for root, _dirs, files in os.walk(ui_dir):
        for name in files:
            if not name.lower().endswith(".tex"):
                continue
            path = os.path.join(root, name)
            info = read_tex(path) or {}
            ovs = info.get("ovs")
            if ovs and ovs < "STATIC":
                unsafe.append((os.path.relpath(path, ui_dir), ovs))
    if unsafe:
        details = "; ".join(f"{path}: ovs={ovs!r}" for path, ovs in unsafe)
        raise ValueError(
            "unsafe JWE3 UI archive order: local OVS names sorting before "
            f"STATIC would put a streamed archive first ({details}). Use a "
            "lowercase, namespaced asset_package/ovs name.")


def default_icon_name_for(sp_conf):
    """The name the GAME will ask for when it wants this species' icon.

    `components.hatchery.lua` builds `"Dinosaurs_Small_" .. sDinoIcon`, and
    `GeneLibraryManager:GetIconForGenome()` resolves sDinoIcon from
    `SpeciesCosmeticSets.DinoIcon` **falling back to the GenomeID**. DinoIcon is
    NULL in all 431 vanilla rows, so the fallback is the only path that ever
    runs and the name is simply the genome / species name.
    """
    return sp_conf.get("genome") or sp_conf.get("name") or ""


def asset_package_gender_subdir(package_name):
    """Return the generated family-member folder for an asset package.

    Match a complete suffix, never a substring: ``female`` contains ``male``,
    which previously sent every ``*_Female`` package into the Male folder.
    Optional numeric suffixes cover family variants without misclassifying a
    species whose own name happens to contain one of these words.
    """
    match = re.search(
        r"_(female|male|juvenile)(?:_\d+)?$",
        (package_name or "").lower())
    if match:
        return match.group(1).capitalize()
    return "Female"


def build_default_icon_set(out_dir, mod_name, plans, report):
    """Give every species a full placeholder icon set.

    Returns `(icon_refs, embedded_files, written)` ready to hand to
    `write_package()`:
      * `icon_refs`     - <types> entries; the .tex/.png pairs are copied out
                          beside them as real OVL entries.
      * `embedded_files` - <files> entries; SVGs are embedded byte-for-byte.

    Asset packages are namespaced per mod rather than reusing vanilla's
    `Dinosaur_Small` / `Dinosaur_Headshot` OVS names, per the project's
    namespace-everything-shared rule.
    """
    icon_refs = []
    embedded = []
    written = []
    kept_png = []

    pkg_ui_dir = os.path.join(out_dir, "UI", mod_name)

    svg_template = None
    if os.path.isfile(PLACEHOLDER_SVG):
        with open(PLACEHOLDER_SVG, "rb") as f:
            svg_template = f.read()
    else:
        report.setdefault("warnings", []).append(
            f"default icons: no placeholder SVG at {PLACEHOLDER_SVG} - "
            f"run extract_ui_svgs.py; tech-tree icons will fall back to the "
            f"donor's vanilla icon.")

    for plan in plans:
        sp_conf = plan.get("config", {})
        species = sp_conf.get("name")
        if not species:
            continue
        icon_name = default_icon_name_for(sp_conf)
        lower = icon_name.lower()

        # --- PNG portraits: referenced by <types>, shipped as .tex/.png ------
        for slot, (stem, segment, prefix) in PLACEHOLDER_PNGS.items():
            src_png = os.path.join(ICON_TEMPLATE_DIR, f"{stem}.png")
            src_tex = os.path.join(ICON_TEMPLATE_DIR, f"{stem}.png.tex")
            if not (os.path.isfile(src_png) and os.path.isfile(src_tex)):
                report.setdefault("warnings", []).append(
                    f"default icons: missing placeholder pair for '{slot}' in "
                    f"{ICON_TEMPLATE_DIR}; skipping that slot.")
                continue

            rel_dir = f"uigameface/img/dinosaurspecies/{segment}"
            base = f"{prefix}_{lower}.png"

            dest_dir = os.path.join(pkg_ui_dir, rel_dir.replace("/", os.sep))
            os.makedirs(dest_dir, exist_ok=True)
            # cobra-tools wants the pair: <name>.png.png is the image, and
            # <name>.png.tex the texture header. Both are needed or the OVL
            # packs without the texture - see the CobblestoneBlock layout.
            #
            asset_package = _default_icon_asset_package(mod_name, slot)

            # Never overwrite: once the placeholder is down, the file on disk
            # may be the author's real art. Regenerating must leave it alone.
            dest_png = os.path.join(dest_dir, base + ".png")
            dest_tex = os.path.join(dest_dir, base + ".tex")

            if os.path.exists(dest_png):
                kept_png.append(f"{rel_dir}/{base}.png")
            else:
                shutil.copyfile(src_png, dest_png)

            if os.path.exists(dest_tex):
                # Preserve the author's image/encoding choices, but migrate a
                # legacy generator-owned uppercase OVS name. Leaving it in
                # place would make the next pack crash even though the newly
                # written PPUIPKG reference is lowercase.
                current = read_tex(dest_tex) or {}
                current_ovs = current.get("ovs", "")
                safe_current = normalise_mod_asset_package(
                    mod_name, current_ovs)
                if current_ovs != safe_current:
                    size = png_size(dest_png) or png_size(src_png)
                    write_tex(
                        dest_tex,
                        size[0] if size else current.get("width", 232),
                        size[1] if size else current.get("height", 232),
                        ovs=safe_current,
                        texel=current.get("texel", DEFAULT_TEXEL),
                        compression=current.get(
                            "compression_type", DEFAULT_COMPRESSION))
                else:
                    kept_png.append(f"{rel_dir}/{base}.tex")
            else:
                # Do NOT just copy the donor .tex: its ovs="Dinosaur_Small"
                # names the VANILLA stream, while the package we emit says
                # <asset_package>Mod_Dinosaur_Small</asset_package>. The header
                # and the reference must name the same stream, so author it.
                size = png_size(dest_png) or png_size(src_png)
                donor = read_tex(src_tex) or {}
                write_tex(dest_tex,
                          size[0] if size else donor.get("width", 232),
                          size[1] if size else donor.get("height", 232),
                          ovs=asset_package,
                          texel=donor.get("texel", DEFAULT_TEXEL),
                          compression=donor.get("compression_type",
                                                DEFAULT_COMPRESSION))

            icon_refs.append((f"{rel_dir}/{base}", asset_package))
            written.append(f"UI/{mod_name}/{rel_dir}/{base}")

        # --- SVG line icon: EMBEDDED in the package, not a separate entry ----
        if svg_template and icon_name:
            embedded.append(
                (f"UIGameface/img/icons/dinosaurSpecies/{icon_name}.svg",
                 svg_template))

    report["default_icons"] = {
        "png_refs": len(icon_refs),
        "svgs_embedded": len(embedded),
        "existing_png_kept": kept_png,
        "note": "placeholder art - replace the files under UI/ with your own; "
                "regenerating will not overwrite them",
    }
    return icon_refs, embedded, written


def plan_species(config):
    """Inspect source dinosaur prefabs and construct generation plan."""
    name = config["name"]
    source = config["source"]
    cosmetics = config.get("cosmetics", {})
    variants = cosmetics.get("variants", 1)
    patterns = cosmetics.get("patterns", 1)

    donor_female_pref = config.get("donor_prefabs", {}).get("Female") or source
    has_female_suffix = donor_female_pref.lower().endswith("_female") or source.lower().endswith("_female")
    fem_target = f"{name}_Female" if has_female_suffix else name

    family_members = config.get("family_members")
    if family_members and isinstance(family_members, list) and len(family_members) > 0:
        members = []
        base_src = source[:-7] if source.endswith("_Female") else source
        for m in family_members:
            if isinstance(m, dict):
                if m.get("enabled") is False or m.get("checked") is False:
                    continue
                m_name = m.get("Name") or m.get("name") or name
                m_pref = m.get("Prefab") or m.get("prefab") or m.get("donor") or source
            elif isinstance(m, (list, tuple)) and len(m) >= 2:
                m_name, m_pref = m[0], m[1]
            else:
                m_name, m_pref = str(m), source

            # Ignore CC variants
            if "cc" in m_name.lower() or "cc" in m_pref.lower():
                continue

            has_fem = m_pref.lower().endswith("_female")
            if m_name == source or m_name == base_src or m_name == f"{base_src}_Female":
                target_prefab_name = f"{name}_Female" if has_fem else name
            elif m_name.startswith(base_src):
                suffix = m_name[len(base_src):]
                target_prefab_name = name + suffix
            elif m_name.startswith(name):
                target_prefab_name = m_name
            else:
                target_prefab_name = f"{name}_{m_name}"

            members.append((target_prefab_name, m_pref))

        if not members:
            members = [
                (fem_target, donor_female_pref),
                (f"{name}_Male", config.get("donor_prefabs", {}).get("Male") or f"{source}_Male"),
                (f"{name}_Juvenile", config.get("donor_prefabs", {}).get("Juvenile") or f"{source}_Juvenile"),
            ]
    else:
        members = [
            (fem_target, donor_female_pref),
            (f"{name}_Male", config.get("donor_prefabs", {}).get("Male") or f"{source}_Male"),
            (f"{name}_Juvenile", config.get("donor_prefabs", {}).get("Juvenile") or f"{source}_Juvenile"),
        ]

    cosmetic_plan = []
    for v in range(1, variants + 1):
        v_str = f"{v:02d}"
        cosmetic_plan.append({
            "name": f"{fem_target}_{v_str}",
            "parent": fem_target,
            "pattern_set": f"{name}_PatternSet_{v_str}",
            "variant_set": f"{name}_VariantSet_{v_str}",
        })
        cosmetic_plan.append({
            "name": f"{name}_Male_{v_str}",
            "parent": f"{name}_Male",
            "pattern_set": f"{name}_PatternSet_{v_str}",
            "variant_set": f"{name}_VariantSet_{v_str}",
        })
        cosmetic_plan.append({
            "name": f"{name}_Juvenile_{v_str}",
            "parent": f"{name}_Juvenile",
            "pattern_set": f"{name}_PatternSet_{v_str}",
            "variant_set": f"{name}_VariantSet_{v_str}",
        })



    report = {"warnings": []}
    return {
        "members": members,
        "cosmetic_plan": cosmetic_plan,
        "variants": variants,
        "patterns": patterns,
    }, report


def serialize_lua_properties(props_dict, indent=8):
    """Serialize a dictionary of property overrides into formatted Lua syntax."""
    if not props_dict:
        return ""
    ind = " " * indent
    lines = []
    for k, v in sorted(props_dict.items()):
        if isinstance(v, dict):
            v = v.get("Default")

        if v is None or v == "" or (isinstance(v, (list, tuple, dict)) and len(v) == 0):
            continue

        if isinstance(v, list):
            items_str = ", ".join(f"'{item}'" for item in v)
            lines.append(f"{ind}{k} = {{\n{ind}    Default = {{ {items_str} }}\n{ind}}},")
        elif isinstance(v, bool):
            lines.append(f"{ind}{k} = {{\n{ind}    Default = {str(v).lower()}\n{ind}}},")
        elif isinstance(v, (int, float)):
            lines.append(f"{ind}{k} = {{\n{ind}    Default = {v}\n{ind}}},")
        elif isinstance(v, str):
            v_str = v.strip()
            if not v_str:
                continue
            lines.append(f"{ind}{k} = {{\n{ind}    Default = '{v_str}'\n{ind}}},")
        else:
            lines.append(f"{ind}{k} = {{\n{ind}    Default = '{v}'\n{ind}}},")
    return "\n".join(lines)


AP_INHERITANCE_MODES = ("Append", "Replace", "Inherit")
AP_INHERITANCE_DEFAULT = "Append"

# '__inheritance' entries are merge DIRECTIVES, not package names - filter them
# out of any user-supplied list before re-emitting it.
_AP_DIRECTIVE_WORDS = {"append", "overwrite", "modify", "prepend", "replace"}


def _resolve_ap_inheritance(config, species_config, member_key, override_dict):
    """Pick the AssetPackages inheritance mode for one family member.

    Resolution order, most specific first: the member's own prefab override,
    then the species setting (either a bare string for the whole family or a
    dict keyed by member), then the mod-wide default, then 'Append'.
    """
    def _norm(v):
        if not v:
            return None
        v = str(v).strip().capitalize()
        return v if v in AP_INHERITANCE_MODES else None

    # 'Adult' and 'Female' name the same member depending on whether the donor's
    # female prefab carries a suffix, so either key may be used to address it.
    keys = [member_key]
    if member_key == "Adult":
        keys.append("Female")
    elif member_key == "Female":
        keys.append("Adult")

    mode = _norm((override_dict or {}).get("AssetPackageInheritance"))
    if mode:
        return mode

    sp = (species_config or {}).get("asset_package_inheritance")
    if isinstance(sp, dict):
        for k in keys + ["Default"]:
            mode = _norm(sp.get(k))
            if mode:
                return mode
    else:
        mode = _norm(sp)
        if mode:
            return mode

    return _norm((config or {}).get("asset_package_inheritance")) or AP_INHERITANCE_DEFAULT


def _asset_packages_block(prefab_name, override, mode, indent=8):
    """Render an AssetPackages property block for a base prefab stub.

    WHY THIS EXISTS: a child prefab's AssetPackages list REPLACES its parent's
    unless it carries an __inheritance directive. A stub that names only its own
    package therefore drops the donor's model and animation packages, and
    nothing reports it - the same silent class as inheriting a missing prefab.
    The dump leans heavily on the directive: 3,395 'Append' against 1,967
    'Overwrite'.

      Append   keep the parent's packages and add ours (default, safe)
      Replace  ours only - the donor's are dropped
      Inherit  emit nothing and ride entirely on the parent
    """
    if mode == "Inherit":
        return ""

    if isinstance(override, dict):
        override = override.get("Default")
    if isinstance(override, str):
        names = [override]
    elif isinstance(override, (list, tuple)):
        names = [str(n) for n in override
                 if str(n).strip().lower() not in _AP_DIRECTIVE_WORDS]
    else:
        names = []
    if not names:
        names = [prefab_name]

    ind = " " * indent
    lines = [f"{ind}AssetPackages = {{", f"{ind}    Default = {{"]
    lines += [f"{ind}        '{n}'," for n in names]
    if mode == "Append":
        lines.append(f"{ind}        __inheritance = 'Append'")
    else:
        lines[-1] = lines[-1].rstrip(",")
    lines += [f"{ind}    }}", f"{ind}}},"]
    return "\n".join(lines)


def _replace_lua_table(src, var_name, body):
    """Swap the contents of `<var> = { ... }` for a generated body."""
    pat = re.compile(re.escape(var_name) + r"\s*=\s*\{.*?\n\}", re.S)
    return pat.sub(f"{var_name} = {{\n{body}\n}}", src)


def _cosmetic_plan_from_fdb(dst_dino_fdb, plan):
    """Rebuild a plan's cosmetic Lua stub list from the ALREADY-CLONED FDB rows,
    instead of a fixed per-config count.

    WHY THIS EXISTS: plan_species() (called before the FDB exists) has no way
    to know how many cosmetic sets a donor actually has, so an earlier version
    generated a fixed `variants`-count worth of stubs (default 1) per member.
    A donor can have far more - Velociraptor has 16 across its 3 members - and
    clone_fdb() (core/database.py) already writes ALL of them into
    SpeciesCosmeticSets with correct, collision-free Prefab names keyed by
    SetID. The result was SpeciesCosmeticSets.Prefab pointing at 13 .lua files
    that were never written - a SILENT dangling reference (the model loads,
    the extra skins just do not exist), the same class of bug fixed once
    already for the same table (see SPECIES_GEN_HANDOFF.md).

    Reading the just-cloned FDB back means the .lua files and the FDB CANNOT
    disagree, because both are now driven by the same rows.
    """
    resolved_members = plan.get("_resolved_members") or []
    if not resolved_members:
        return plan.get("cosmetic_plan", [])

    sid_to_member = {m["target_sid"]: m for m in resolved_members}
    target_sids = list(sid_to_member.keys())
    if not target_sids:
        return []

    con = sqlite3.connect(f"file:{dst_dino_fdb}?mode=ro", uri=True)
    try:
        cols_info = con.execute('PRAGMA table_info("SpeciesCosmeticSets")').fetchall()
        cols = [c[1] for c in cols_info]
        if not cols or not {"SpeciesID", "SetID", "Prefab"}.issubset(cols):
            return []
        ph = ",".join("?" * len(target_sids))
        rows = con.execute(
            f'SELECT SpeciesID, SetID, Prefab FROM "SpeciesCosmeticSets" '
            f'WHERE SpeciesID IN ({ph})', target_sids).fetchall()
    finally:
        con.close()

    new_name = plan["config"]["name"]
    cosmetic_plan = []
    for sid, set_id, prefab in rows:
        member = sid_to_member.get(sid)
        if member is None or not prefab:
            continue
        nn = f"{int(set_id or 1):02d}"
        cosmetic_plan.append({
            # the exact name the FDB references - no drift possible
            "name": prefab,
            # the PREFAB to inherit, never target_name: they diverge for a
            # donor whose female prefab is suffixed (Dimetrodon), and an
            # inherited prefab that does not exist renders nothing, silently.
            "parent": member["target_prefab"],
            "pattern_set": f"{new_name}_PatternSet_{nn}",
            "variant_set": f"{new_name}_VariantSet_{nn}",
        })
    return cosmetic_plan


def normalise_scale_range(value, fallback=1.0):
    """Coerce one `scales` entry into a `(min, max)` pair.

    Accepts a bare number (fixed size, `min == max`, which is how every mod
    generated before size variation existed is expressed), a two-element
    list/tuple, or a dict with min/max keys. Planet Zoo's own bands are the
    reference shape: `SizeData.MinScaleFemale` / `MaxScaleFemale` etc.
    """
    lo = hi = None
    if isinstance(value, dict):
        for lo_key in ("min", "fMin", "Min", "MinScale"):
            if value.get(lo_key) is not None:
                lo = value[lo_key]
                break
        for hi_key in ("max", "fMax", "Max", "MaxScale"):
            if value.get(hi_key) is not None:
                hi = value[hi_key]
                break
        # A dict carrying only one bound is a fixed size, not half a band.
        if lo is None:
            lo = hi
        if hi is None:
            hi = lo
    elif isinstance(value, (list, tuple)) and len(value) >= 2:
        lo, hi = value[0], value[1]
    else:
        lo = hi = value

    try:
        lo = float(lo)
        hi = float(hi)
    except (ValueError, TypeError):
        return None

    if hi < lo:
        lo, hi = hi, lo
    return (lo, hi)


def write_scale_module(main_dir, mod_name, scaling_map, report):
    """Write `<ModName>ScaleData.lua` and `Components.<ModName>ScaleController.lua`."""
    if not scaling_map:
        return None

    path_primary = SCALE_TEMPLATE
    path_fallback = SCALE_TEMPLATE_FALLBACK
    tmpl_path = path_primary if os.path.isfile(path_primary) else path_fallback

    if not os.path.isfile(tmpl_path):
        report.setdefault("warnings", []).append(
            f"Scale template missing at both {path_primary} and {path_fallback}")
        return None

    with open(tmpl_path, "r", encoding="utf-8") as f:
        tmpl = f.read()

    by_id = {}
    by_name = {}
    for k, v in scaling_map.items():
        rng = normalise_scale_range(v)
        if rng is None:
            continue
        try:
            by_id[int(k)] = rng
        except (ValueError, TypeError):
            by_name[str(k)] = rng

    def _band(rng):
        return "{{ fMin = {0}, fMax = {1} }}".format(_lua_num(rng[0]), _lua_num(rng[1]))

    id_lines = [f"        [{sid}] = {_band(rng)}," for sid, rng in sorted(by_id.items())]
    name_lines = [f'        ["{sname}"] = {_band(rng)},'
                  for sname, rng in sorted(by_name.items())]

    out = _replace_lua_table(tmpl, "MDDeinosuchusScaleData.tRenderScalesBySpeciesID", "\n".join(id_lines))
    out = _replace_lua_table(out, "MDDeinosuchusScaleData.tRenderScalesByGenome", "\n".join(name_lines))
    out = _apply_scale_mod_name(out, mod_name, by_name)

    file_name = f"database.{mod_name.lower()}scaledata.lua"
    out_path = os.path.join(main_dir, file_name)
    _write_generated_lua(out_path, out)

    written = [file_name]

    # The controller is the lifecycle half: without it nothing re-applies
    # the scale and nothing is written into the save.
    if os.path.isfile(SCALE_CONTROLLER_TEMPLATE):
        with open(SCALE_CONTROLLER_TEMPLATE, "r", encoding="utf-8") as f:
            ctrl = f.read()
        ctrl = _apply_scale_mod_name(ctrl, mod_name, by_name)
        ctrl_name = f"components.{mod_name.lower()}scalecontroller.lua"
        _write_generated_lua(os.path.join(main_dir, ctrl_name), ctrl)
        written.append(ctrl_name)
    else:
        report.setdefault("warnings", []).append(
            "Scale controller template missing at "
            f"{SCALE_CONTROLLER_TEMPLATE}; sizes will not persist across a save.")

    report["scaling"] = {
        "by_species_id": {k: list(v) for k, v in by_id.items()},
        "by_name": {k: list(v) for k, v in by_name.items()},
        "files": written,
    }
    return file_name


def _lua_num(value):
    """Render a float without Python's trailing-zero noise."""
    text = f"{float(value):.4f}".rstrip("0").rstrip(".")
    return text or "0"


def _apply_scale_mod_name(src, mod_name, by_name):
    """Rename the template's Deinosuchus placeholders to this mod.

    The lowercase pass matters: ACSE exposes a component manager as
    `api.<lowercased component name>`, and the controller is required by the
    lowercase module path, so `MDDeinosuchus` alone is not enough.
    """
    src = re.sub(r"MDDeinosuchusScaleData", f"{mod_name}ScaleData", src)
    src = re.sub(r"MDDeinosuchus", mod_name, src)
    src = re.sub(r"mddeinosuchus", mod_name.lower(), src)
    for sname in sorted(by_name.keys()):
        base_sname = sname.split("_")[0]
        src = re.sub(r"Deinodoots", f"{base_sname}s", src)
        src = re.sub(r"Deinodoot", base_sname, src)
    return src


def audit_asset_packages(main_dir, init_dir, report):
    """Audit referenced vs defined asset package files."""
    referenced = set()
    pat = re.compile(r"""AssetPackageLoader\s*=\s*\{\s*PackageNames\s*=\s*\{\s*['"]([^'"]+)['"]""")

    # The species stubs are built on the PROPERTY form - the dinosaur's main
    # Properties block, where AssetPackages sits alongside ModelName,
    # MotionGraphName and MaterialLayersName. This audit previously matched only
    # the AssetPackageLoader component, which the stubs never emit, so every
    # generated package reference went unchecked and the audit always passed.
    # '__inheritance' entries are merge directives, not package names (§3e).
    prop_pat = re.compile(r"AssetPackages\s*=\s*\{\s*Default\s*=\s*\{(.*?)\}", re.S)
    name_pat = re.compile(r"""['"]([^'"]+)['"]""")

    for root, _, files in os.walk(main_dir):
        for file in files:
            if not file.endswith(".lua"):
                continue
            path = os.path.join(root, file)
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                src = f.read()
            for line in src.splitlines():
                m = pat.search(line)
                if m:
                    referenced.add(m.group(1))
            for m in prop_pat.finditer(src):
                for name in name_pat.findall(m.group(1)):
                    if name.strip().lower() not in _AP_DIRECTIVE_WORDS:
                        referenced.add(name)

    existing = set()
    if os.path.isdir(init_dir):
        for file in os.listdir(init_dir):
            if file.endswith(".assetpkg"):
                existing.add(os.path.splitext(file)[0])

    # .assetpkg files are written lowercased while a prefab references its
    # package in CamelCase ('Deinodoot_Female' vs deinodoot_female.assetpkg),
    # so this comparison has to be case-insensitive or every package reads as
    # missing.
    existing_lower = {e.lower() for e in existing}
    missing = sorted(r for r in referenced if r.lower() not in existing_lower)
    if missing:
        report.setdefault("warnings", []).append(
            f"Asset packages referenced in Lua but missing .assetpkg: {missing}")

    return referenced, existing


def write_scaffold(out_dir, mod_name, plans, config, report):
    """Write prefab Luas, cosmetic Luas, database manifests, and AssetPackages."""
    main_dir = os.path.join(out_dir, "Main")
    init_dir = os.path.join(out_dir, "Init")
    os.makedirs(main_dir, exist_ok=True)
    os.makedirs(init_dir, exist_ok=True)
    written = []

    all_prefab_names = []
    ui_rewards = []
    nodes = []
    rebirth_rewards = []
    ingen_data = []
    ingen_techtree = []
    ingen_genomes = []

    for plan in plans:
        new_name = plan["config"]["name"]
        members = plan["members"]
        cosmetic_plan = plan.get("cosmetic_plan", [])
        prefab_overrides = plan["config"].get("prefab_overrides", {})

        # Prefab Luas
        for prefab_name, default_donor in members:
            member_key = "Adult"
            if prefab_name.lower() != new_name.lower():
                member_key = prefab_name[len(new_name):].lstrip('_')
            if not member_key:
                member_key = "Adult"

            override_dict = (
                prefab_overrides.get(member_key)
                or prefab_overrides.get("Female" if member_key == "Adult" else member_key, {})
                or {}
            )
            donor = override_dict.get("Prefab") or default_donor

            # AssetPackages is emitted separately from the other properties:
            # serialize_lua_properties() cannot express the __inheritance
            # directive, and without it the stub's list would silently replace
            # the donor's packages. Copy first so a user's config is not mutated.
            props = dict(override_dict.get("Properties", {}) or {})
            ap_override = props.pop("AssetPackages", None)
            ap_mode = _resolve_ap_inheritance(
                config, plan["config"], member_key, override_dict)

            props_str = serialize_lua_properties(props, indent=8)
            ap_block = _asset_packages_block(prefab_name, ap_override, ap_mode, indent=8)
            if ap_block:
                props_str = f"{props_str}\n{ap_block}" if props_str else ap_block
                if ap_mode == "Replace":
                    report.setdefault("warnings", []).append(
                        f"{prefab_name}: AssetPackages set to Replace, so the donor's "
                        f"packages ({donor or 'inherited'}) are dropped. The model and "
                        f"animations will not resolve unless your own OVL supplies them."
                    )

            path = os.path.join(main_dir, f"{prefab_name.lower()}.lua")
            _write_generated_lua(
                path, PREFAB_LUA.format(mod=prefab_name, name=prefab_name,
                                        donor=donor or "", properties=props_str))
            written.append(os.path.basename(path))
            all_prefab_names.append(prefab_name)

        # Cosmetic variant Luas
        for cosm in cosmetic_plan:
            path = os.path.join(main_dir, f"{cosm['name'].lower()}.lua")
            _write_generated_lua(path, COSMETIC_LUA.format(
                mod=cosm["name"], name=cosm["name"],
                parent=cosm["parent"], pattern_set=cosm["pattern_set"],
                variant_set=cosm["variant_set"],
            ))
            written.append(os.path.basename(path))
            all_prefab_names.append(cosm["name"])


        # Tech tree accumulators
        # With no custom icon, reuse the donor's known-good vanilla icon.
        icon = plan["config"].get("icon") or plan["config"].get("source") or new_name
        ui_rewards.append(f'    TechTree_{new_name} = {{\n        icon = "",\n        label = "{new_name}"\n    }}')
        nodes.append(f'    {new_name}1A = {{\n        streamedIcon = "icons.dinosaurSpecies.{icon}",\n        image = "{icon}",\n        conditions = {{\n            {{preset = "Rating", Target = "0"}}\n        }},\n        rewards = {{\n            {{id = "TechTree_{new_name}"}}\n        }}\n    }}')
        rebirth_rewards.append(f'                    {{id = "TechTree_{new_name}"}}')
        ingen_data.append(f'        {new_name} = {{}}')
        ingen_techtree.append(f'        "TechTree_{new_name}"')
        ingen_genomes.append(f'"{new_name}"')

    ui_rewards_str = ",\n".join(ui_rewards)
    nodes_str = ",\n".join(nodes)
    rebirth_rewards_str = ",\n".join(rebirth_rewards)
    ingen_data_str = ",\n".join(ingen_data)
    ingen_techtree_str = ",\n".join(ingen_techtree)
    ingen_genomes_str = ", ".join(ingen_genomes)

    # PrefabData
    prefab_list = "\n".join(f"\t\t'{p}'," for p in all_prefab_names)
    path = os.path.join(main_dir, f"database.{mod_name.lower()}prefabdata.lua")

    _write_generated_lua(
        path, PREFABDATA_LUA.format(mod_name=mod_name, prefab_list=prefab_list))
    written.append(os.path.basename(path))

    # Icon Mount and PPUIPKG. An empty list means exactly "no custom icons";
    # never fabricate an icon entry because merely mounting a broken UI OVL can
    # crash JWE3 during startup.
    icons = list(config.get("icons") or [])

    # Optional placeholder set: gives every species a full complement of icons
    # (PNG portraits + tech-tree SVG) so no slot is blank before the author has
    # any art. Explicit `icons` still win - this only fills in.
    default_icon_refs, default_svgs, default_written = [], [], []
    if config.get("default_icons"):
        default_icon_refs, default_svgs, default_written = build_default_icon_set(
            out_dir, mod_name, plans, report)
        written.extend(default_written)

    # Remove manager/package definitions left by a previous enabled build.
    icon_lua_path = os.path.join(main_dir, f"managers.{mod_name.lower()}iconmount.lua")
    has_icons = bool(icons or default_icon_refs or default_svgs)
    if not has_icons and os.path.isfile(icon_lua_path):
        os.remove(icon_lua_path)
    if not has_icons:
        ui_root = os.path.join(out_dir, "UI")
        if os.path.isdir(ui_root):
            for root, _dirs, files in os.walk(ui_root):
                for fname in files:
                    if fname.lower().endswith(".ppuipkg"):
                        os.remove(os.path.join(root, fname))

    # Match CobblestoneBlock exactly: one dedicated UI overlay named for the
    # mod. The icon's `asset_package` is an internal OVS name and is NOT the
    # overlay/folder name (Cobblestone uses overlay `CobblestoneBlock` with
    # asset package `images_cobblestoneblock_decoration`).
    overlay_entries = f'\t{{"{mod_name}", "{mod_name}/UI/{mod_name}"}}'
    if has_icons:
        _write_generated_lua(
            icon_lua_path, ICON_MOUNT_LUA.format(
                mod_name=mod_name, overlay_entries=overlay_entries))
        written.append(os.path.basename(icon_lua_path))
    # NOTE: deliberately NOT added to _tContentToCall. This is an ACSE MANAGER
    # (it has Init/Advance and ends in VerifyManagerModule), so it is registered
    # through AddLuaManagers instead - see icon_manager_entry below. Requiring a
    # manager as content is what put the icon code on the boot path.
    icon_require = ""

    if has_icons:
        pkg_name = mod_name
        pkg_ui_dir = os.path.join(out_dir, "UI", mod_name)
        os.makedirs(pkg_ui_dir, exist_ok=True)
        ppuipkg_path = os.path.join(pkg_ui_dir, f"userinterfaceimages{pkg_name.lower()}.ppuipkg")

        # <types> - REFERENCES to .tex/.png that ship as separate OVL entries.
        icon_refs = []
        seen_cfg = set()
        for icon in icons:
            img_path = icon.get("path") or icon.get("image_name") or f"uigameface/img/dinosaurs/{mod_name.lower()}.png"
            asset_package = normalise_mod_asset_package(
                mod_name,
                icon.get("assetPackage")
                or icon.get("asset_package")
                or mod_name)
            if img_path in seen_cfg:
                continue
            seen_cfg.add(img_path)
            icon_refs.append((img_path, asset_package))

            norm_img_path = img_path.replace("/", os.sep).replace("\\", os.sep)
            dir_name = os.path.dirname(norm_img_path)
            if dir_name:
                os.makedirs(os.path.join(pkg_ui_dir, dir_name), exist_ok=True)

        # De-dupe by image_name. The GUI's icon list is populated by reading the
        # mod's OWN package back (syncIconsFromMod), so on the second run the
        # default set arrives twice: once via config["icons"] and once from
        # build_default_icon_set. Explicit config entries win - the author may
        # have retyped an asset package - so this is first-wins, not last.
        seen_refs = {img for img, _pkg in icon_refs}
        for img, pkg in default_icon_refs:
            if img not in seen_refs:
                seen_refs.add(img)
                icon_refs.append((img, pkg))

        # <files> - whole files EMBEDDED byte-for-byte. This is the only way an
        # SVG can ship; there is no loose .svg entry anywhere in the game.
        #
        # REGENERATING MUST NOT DESTROY ART. The embedded bytes ARE the icon -
        # unlike a .png, an author's custom SVG lives nowhere else on disk, so
        # blindly rewriting this package would silently delete it. Same trap
        # that let Capiraptor's hand-tuned scale maxima drift away from its
        # project file. So:
        #   <files>  author wins  - an existing entry is never overwritten, and
        #                           entries we did not generate are preserved.
        #   <types>  generator wins on names it owns (they are just references,
        #                           derived from config), unknown ones preserved.
        existing_files, existing_icons = [], []
        if os.path.isfile(ppuipkg_path):
            try:
                _basic, existing_files, existing_icons = read_package(ppuipkg_path)
            except Exception as exc:
                report.setdefault("warnings", []).append(
                    f"could not parse the existing {os.path.basename(ppuipkg_path)} "
                    f"({exc}). It will be REPLACED - any custom SVGs inside it are "
                    f"lost. Move it aside and re-inject them.")
                existing_files, existing_icons = [], []

        existing_names = {name for name, _ in existing_files}
        merged_files = list(existing_files)
        for name, data in default_svgs:
            if name not in existing_names:
                merged_files.append((name, data))

        generated_refs = {img for img, _pkg in icon_refs}
        merged_icons = list(icon_refs)
        for img, pkg in existing_icons:
            if img not in generated_refs:
                merged_icons.append((img, pkg))

        kept = len(existing_names)
        if kept:
            report.setdefault("preserved_ppuipkg_files", []).extend(sorted(existing_names))

        write_package(ppuipkg_path, f"{pkg_name}/UI",
                      files=merged_files, icons=merged_icons)
        audit_ui_texture_archives(pkg_ui_dir)
        written.append(os.path.relpath(ppuipkg_path, out_dir))

    # Aggregate scaling across all species and family member units
    scaling = dict(config.get("scaling") or {})
    for plan in plans:
        sp_conf = plan.get("config", {})
        if sp_conf.get("scaling_enabled") is False:
            continue
        sp_name = sp_conf.get("name")
        sp_id = sp_conf.get("species_id")

        base_scale = sp_conf.get("scale")
        if base_scale is None:
            base_scale = 1.0
        # A species-level `scale` may itself be a band, so the per-morph
        # fallback is a (min, max) pair rather than a single float.
        base_scale_val = normalise_scale_range(base_scale) or (1.0, 1.0)

        sp_scales = sp_conf.get("scales") or {}
        prefab_overrides = sp_conf.get("prefab_overrides") or {}
        resolved_members = plan.get("_resolved_members") or []

        if resolved_members:
            for rm in resolved_members:
                m_key = rm.get("key", "Female")
                m_sid = rm.get("target_sid")
                m_name = rm.get("target_name")

                m_override = prefab_overrides.get(m_key, {})
                m_scale_val = (
                    sp_scales.get(m_key)
                    if sp_scales.get(m_key) is not None
                    else m_override.get("scale")
                    or m_override.get("RenderScaleMultiplier")
                    or base_scale_val
                )
                s_val = normalise_scale_range(m_scale_val) or base_scale_val

                if m_sid:
                    scaling[int(m_sid)] = s_val
                if m_name:
                    scaling[m_name] = s_val
                if m_key == "Female" and sp_name:
                    scaling[sp_name] = s_val
        else:
            # Default fallback for Female, Male, Juvenile
            defaults = [
                ("Female", sp_id, sp_name),
                ("Male", (int(sp_id) + 1) if sp_id else None, f"{sp_name}_Male" if sp_name else None),
                ("Juvenile", (int(sp_id) + 2) if sp_id else None, f"{sp_name}_Juvenile" if sp_name else None),
            ]
            for m_key, m_sid, m_name in defaults:
                m_override = prefab_overrides.get(m_key, {})
                m_scale_val = (
                    sp_scales.get(m_key)
                    if sp_scales.get(m_key) is not None
                    else m_override.get("scale")
                    or m_override.get("RenderScaleMultiplier")
                    or base_scale_val
                )
                s_val = normalise_scale_range(m_scale_val) or base_scale_val

                if m_sid:
                    scaling[int(m_sid)] = s_val
                if m_name:
                    scaling[m_name] = s_val

    config["scaling"] = scaling


    # LuaDatabase
    path = os.path.join(main_dir, f"database.{mod_name.lower()}luadatabase.lua")
    _write_generated_lua(path, LUADATABASE_LUA.format(
        mod_name=mod_name,
        manager_block=(ICON_MANAGER_DATABASE_BLOCK.format(mod_name=mod_name)
                       if has_icons else ""),
        self_content=(f"    table.insert(_tContentToCall, {mod_name}Database)\n"
                      if has_icons else ""),
        scale_require=(SCALE_REQUIRE.format(mod_name=mod_name)
                       if config.get("scaling") else ""),
        icon_require=icon_require))
    written.append(os.path.basename(path))

    # Tech tree
    path = os.path.join(main_dir, f"database.{mod_name.lower()}techtreedata.lua")
    _write_generated_lua(
        path, TECHTREE_LUA.format(
            mod_name=mod_name, ui_rewards=ui_rewards_str, nodes=nodes_str))
    written.append(os.path.basename(path))

    # Rebirth hidden species tech tree
    path = os.path.join(main_dir, f"database.{mod_name.lower()}rebirthhiddenspeciestechtree.lua")
    _write_generated_lua(
        path, REBIRTH_TECHTREE_LUA.format(
            mod_name=mod_name, rebirth_rewards=rebirth_rewards_str))
    written.append(os.path.basename(path))

    # InGen database
    path = os.path.join(main_dir, f"database.{mod_name.lower()}ingendatabasedata.lua")
    _write_generated_lua(path, INGEN_DATABASE_LUA.format(
        mod_name=mod_name, ingen_data=ingen_data_str,
        ingen_techtree=ingen_techtree_str,
        ingen_genomes=ingen_genomes_str))
    written.append(os.path.basename(path))

    # Shared Dinosaur Mods tech tree
    path = os.path.join(main_dir, "techtrees.trees.dinosaurmodstechtree.lua")
    _write_generated_lua(path, DINOSAUR_MODS_TECHTREE_LUA)
    written.append(os.path.basename(path))

    # Init database config
    path = os.path.join(init_dir, f"databases.{mod_name.lower()}.lua")
    _write_generated_lua(path, INIT_DATABASE_LUA.format(mod_name=mod_name))
    written.append(f"Init/{os.path.basename(path)}")

    # Manifest
    with open(os.path.join(out_dir, "Manifest.xml"), "w") as f:
        f.write(MANIFEST_XML.format(name=mod_name, uuid=config["uuid"]))
    written.append("Manifest.xml")

    # Optional per-species scaling
    scaling = config.get("scaling")
    if scaling:
        fn = write_scale_module(main_dir, mod_name, scaling, report)
        if fn:
            written.append(fn)
    else:
        stale_scale = os.path.join(main_dir, f"database.{mod_name.lower()}scaledata.lua")
        if os.path.isfile(stale_scale):
            os.remove(stale_scale)

    # AssetPackages
    referenced, _ = audit_asset_packages(main_dir, init_dir, report)
    members_only = {p for p in all_prefab_names if not re.search(r"_\d{2}$", p)}
    mod_owned = set(members_only) | {
        r for r in referenced
        if r.lower() in {p.lower() for p in all_prefab_names}
        or r.lower().startswith(mod_name.lower())}

    root_ap = config.get("asset_packages") or {}
    if not isinstance(root_ap, dict):
        raise ValueError("asset_packages must be an object mapping package names to paths")
    category = config.get("asset_category") or "Land"

    # Every row in the Asset Packages editor is an output instruction. Its key
    # is the exact .assetpkg basename and its value is the exact OVL asset path.
    # Configured casing wins over an inferred prefab package with the same name.
    package_names = {str(pkg).lower(): str(pkg) for pkg in mod_owned}
    for configured_name, configured_path in root_ap.items():
        if not isinstance(configured_name, str) or not configured_name:
            raise ValueError("Asset-package names must be non-empty strings")
        if not isinstance(configured_path, str) or not configured_path.strip():
            raise ValueError(f"Asset package {configured_name!r} must have a non-empty path")
        package_names[configured_name.lower()] = configured_name

    for pkg in sorted(package_names.values(), key=str.lower):
        validate_output_identifier(pkg, "Generated asset-package name")
        pkg_file = _exact_case_output_path(init_dir, f"{pkg}.assetpkg")

        raw_path = root_ap.get(pkg)
        if not raw_path:
            raw_path = next((value for key, value in root_ap.items()
                             if str(key).lower() == pkg.lower()), None)
        if not raw_path:
            base_sp_name = None
            for p in plans:
                sp_n = p["config"]["name"]
                if pkg.lower().startswith(sp_n.lower()):
                    base_sp_name = sp_n
                    break
            if not base_sp_name:
                base_sp_name = pkg.split('_')[0]

            gender_sub = asset_package_gender_subdir(pkg)

            raw_path = f"ovldata\\{mod_name}\\Dinosaurs\\{category}\\{base_sp_name}\\{gender_sub}\\{pkg}"

        asset_path_str = raw_path.replace("/", "\\")
        if not asset_path_str.lower().startswith("ovldata\\"):
            clean_path = asset_path_str.lstrip("\\/")
            asset_path_str = f"ovldata\\{mod_name}\\{clean_path}"
        path_parts = [part for part in asset_path_str.split("\\") if part]
        if any(part in (".", "..") for part in path_parts):
            raise ValueError(f"Asset package {pkg!r} contains path traversal: {asset_path_str!r}")


        xml_content = (
            f'<AssetpkgRoot game="Jurassic World Evolution 3">\n'
            f'\t<asset_path>{asset_path_str}</asset_path>\n'
            f'</AssetpkgRoot>\n'
        )
        with open(pkg_file, "w", encoding="utf-8") as f:
            f.write(xml_content)
        written.append(f"Init/{os.path.basename(pkg_file)}")

        rel_folder = asset_path_str
        ovl_prefix = f"ovldata\\{mod_name}\\".lower()
        if rel_folder.lower().startswith(ovl_prefix):
            rel_folder = rel_folder[len(ovl_prefix):]
            pkg_dir = os.path.normpath(os.path.join(out_dir, rel_folder))
            if os.path.commonpath([os.path.realpath(out_dir), os.path.realpath(pkg_dir)]) != os.path.realpath(out_dir):
                raise ValueError(f"Asset package {pkg!r} escapes the generated mod directory")
            os.makedirs(pkg_dir, exist_ok=True)
            written.append(rel_folder.replace("\\", "/"))



    report["files_written"] = written
    return written




def _load_ownership(out_dir):
    path = os.path.join(out_dir, OWNERSHIP_FILE)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as stream:
            data = json.load(stream)
        return data.get("files", {}) if isinstance(data, dict) else {}
    except (OSError, ValueError):
        return {}


def _load_protected_files(out_dir):
    path = os.path.join(out_dir, OWNERSHIP_FILE)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as stream:
            data = json.load(stream)
        protected = data.get("protected", {}) if isinstance(data, dict) else {}
        return protected if isinstance(protected, dict) else {}
    except (OSError, ValueError):
        return {}


def _normalise_written_paths(out_dir, written):
    owned = set()
    for item in written:
        rel = str(item).replace("\\", "/")
        direct = os.path.join(out_dir, *rel.split("/"))
        main = os.path.join(out_dir, "Main", *rel.split("/"))
        path = direct if os.path.isfile(direct) else main
        if os.path.isfile(path):
            owned.add(os.path.relpath(path, out_dir).replace("\\", "/"))
    return owned


def _snapshot_modified_owned(out_dir, ownership, protected=None):
    saved = {}
    for rel, expected in ownership.items():
        path = os.path.join(out_dir, *rel.split("/"))
        if os.path.isfile(path) and _sha256(path) != expected:
            with open(path, "rb") as stream:
                saved[rel] = stream.read()
    for rel in (protected or {}):
        path = os.path.join(out_dir, *rel.split("/"))
        if os.path.isfile(path):
            with open(path, "rb") as stream:
                saved[rel] = stream.read()
    return saved


def _reconcile_owned_files(out_dir, old_ownership, current_owned,
                           modified_snapshots, report):
    conflicts = []
    protected_files = {}
    current_by_case = {rel.casefold(): rel for rel in current_owned}
    modified_by_case = {rel.casefold(): (rel, content)
                        for rel, content in modified_snapshots.items()}
    tracked_paths = set(old_ownership) | set(modified_snapshots)
    for rel in tracked_paths:
        old_hash = old_ownership.get(rel)
        current_rel = current_by_case.get(rel.casefold())
        modified_entry = modified_by_case.get(rel.casefold())
        effective_rel = current_rel or rel
        path = os.path.join(out_dir, *effective_rel.split("/"))
        if modified_entry is not None:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "wb") as stream:
                stream.write(modified_entry[1])
            conflicts.append(effective_rel)
            protected_files[effective_rel] = hashlib.sha256(
                modified_entry[1]).hexdigest()
            if current_rel:
                current_owned.discard(current_rel)
        elif old_hash is not None and current_rel is None and os.path.isfile(path):
            if _sha256(path) == old_hash:
                os.remove(path)
            else:
                conflicts.append(rel)

    if conflicts:
        report.setdefault("warnings", []).append(
            "Preserved and protected hand-edited generator files: "
            + ", ".join(sorted(conflicts)))
        report["preserved_generated_file_conflicts"] = sorted(conflicts)

    files = {}
    for rel in sorted(current_owned):
        path = os.path.join(out_dir, *rel.split("/"))
        if os.path.isfile(path):
            files[rel] = _sha256(path)
    with open(os.path.join(out_dir, OWNERSHIP_FILE), "w", encoding="utf-8") as stream:
        json.dump({"version": 2, "files": files, "protected": protected_files},
                  stream, indent=2, sort_keys=True)


def _resolve_project_uuid(config, existing_out):
    candidate = None
    manifest = os.path.join(existing_out, "Manifest.xml")
    if os.path.isfile(manifest):
        try:
            with open(manifest, "r", encoding="utf-8") as stream:
                match = re.search(r"<ID>\s*([^<]+)\s*</ID>", stream.read())
            candidate = match.group(1).strip() if match else None
        except OSError:
            candidate = None
    if not candidate:
        project_path = os.path.join(existing_out, "mod_project.json")
        if os.path.isfile(project_path):
            try:
                with open(project_path, "r", encoding="utf-8") as stream:
                    candidate = json.load(stream).get("uuid")
            except (OSError, ValueError, AttributeError):
                candidate = None
    if not candidate:
        candidate = config.get("uuid")
    if candidate:
        try:
            return str(uuid_mod.UUID(str(candidate)))
        except (ValueError, TypeError, AttributeError) as exc:
            raise ValueError(f"Project UUID is malformed: {candidate!r}") from exc
    return str(uuid_mod.uuid4())


def _collect_generated_project_ids(output_root, current_mod_name):
    """Reserve IDs already emitted by sibling generated projects."""
    species_ids = set()
    genetic_ids = set()
    if not os.path.isdir(output_root):
        return species_ids, genetic_ids

    for entry in os.scandir(output_root):
        if (not entry.is_dir(follow_symlinks=False) or entry.is_symlink()
                or entry.name.startswith('.')
                or entry.name.casefold() == current_mod_name.casefold()):
            continue

        project_path = os.path.join(entry.path, "mod_project.json")
        try:
            with open(project_path, "r", encoding="utf-8") as stream:
                project = json.load(stream)
            for species in project.get("species", []):
                base_id = species.get("species_id")
                genetic_id = species.get("genetic_id")
                if isinstance(base_id, int) and not isinstance(base_id, bool):
                    enabled = [member for member in (species.get("family_members") or [])
                               if not isinstance(member, dict)
                               or (member.get("enabled") is not False
                                   and member.get("checked") is not False)]
                    family_width = max(3, len(enabled))
                    species_ids.update(range(base_id, base_id + family_width))
                if isinstance(genetic_id, int) and not isinstance(genetic_id, bool):
                    genetic_ids.add(genetic_id)
        except (OSError, ValueError, AttributeError, TypeError):
            pass

        main_dir = os.path.join(entry.path, "Main")
        if not os.path.isdir(main_dir):
            continue
        for filename in os.listdir(main_dir):
            if not filename.lower().endswith("dinosaurs.fdb"):
                continue
            fdb_path = os.path.join(main_dir, filename)
            try:
                con = sqlite3.connect(f"file:{fdb_path}?mode=ro", uri=True)
                try:
                    for species_id, genetic_id in con.execute(
                            "SELECT SpeciesID, GeneticSpeciesID FROM Species"):
                        if species_id is not None:
                            species_ids.add(int(species_id))
                        if genetic_id is not None:
                            genetic_ids.add(int(genetic_id))
                finally:
                    con.close()
            except (OSError, sqlite3.Error, TypeError, ValueError):
                continue
    return species_ids, genetic_ids


def _validate_staging(out_dir, plans, dino_fdb, exp_fdb):
    for path in (dino_fdb, exp_fdb):
        con = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
        try:
            result = con.execute("PRAGMA integrity_check").fetchone()
            if result != ("ok",):
                raise RuntimeError(f"SQLite integrity check failed for {path}: {result}")
        finally:
            con.close()

    con = sqlite3.connect(f"file:{dino_fdb}?mode=ro", uri=True)
    try:
        expected = []
        for plan in plans:
            expected.extend((m["target_sid"], m["target_name"], m["target_prefab"])
                            for m in plan.get("_resolved_members") or [])
        for sid, name, prefab in expected:
            row = con.execute(
                "SELECT Name, Prefab FROM Species WHERE SpeciesID=?", (sid,)).fetchone()
            if row != (name, prefab):
                raise RuntimeError(
                    f"Staging identity validation failed for SpeciesID {sid}: "
                    f"expected {(name, prefab)!r}, found {row!r}")
        prefab_refs = {r[0] for r in con.execute(
            "SELECT Prefab FROM Species WHERE Prefab IS NOT NULL UNION "
            "SELECT Prefab FROM SpeciesCosmeticSets WHERE Prefab IS NOT NULL")}
    finally:
        con.close()
    main_dir = os.path.join(out_dir, "Main")
    generated_names = {
        os.path.splitext(name)[0].lower() for name in os.listdir(main_dir)
        if name.lower().endswith(".lua") and not name.lower().startswith(
            ("database.", "managers.", "techtrees."))}
    missing = sorted(p for p in prefab_refs if p.lower() not in generated_names)
    if missing:
        raise RuntimeError(f"Generated prefab references have no matching Main Lua: {missing}")

    audit_report = {"warnings": []}
    referenced, existing = audit_asset_packages(
        main_dir, os.path.join(out_dir, "Init"), audit_report)
    expected_owned = {r for r in referenced if any(
        r.lower().startswith(plan["config"]["name"].lower()) for plan in plans)}
    existing_lower = {e.lower() for e in existing}
    missing_owned = sorted(r for r in expected_owned if r.lower() not in existing_lower)
    if missing_owned:
        raise RuntimeError(f"Generated asset packages are missing: {missing_owned}")


def _build_species(out_dir, mod_name, plans, report, config):
    """Build a complete project into an already-created staging directory."""
    main_dir = os.path.join(out_dir, "Main")
    os.makedirs(main_dir, exist_ok=True)

    src_dino_fdb = config.get("source_dinosaurs_fdb") or os.path.join(BASE_DIR, "extracted_fdbs", "c0dinosaurs.fdb")
    src_exp_fdb = config.get("source_expeditions_fdb") or os.path.join(BASE_DIR, "extracted_fdbs", "c0expeditions.fdb")

    dst_dino_fdb = os.path.join(main_dir, f"{mod_name.lower()}dinosaurs.fdb")
    dst_exp_fdb = os.path.join(main_dir, f"{mod_name.lower()}expeditions.fdb")

    for _fdb in (dst_dino_fdb, dst_exp_fdb):
        if os.path.isfile(_fdb):
            os.remove(_fdb)

    # Clone dinosaurs.fdb & expeditions.fdb
    for plan in plans:
        sp_conf = plan["config"]
        fdb_ov = dict(sp_conf.get("fdb_overrides", {}))
        if "family_members" in sp_conf:
            fdb_ov["family_members"] = sp_conf["family_members"]
        # cosmetics.film_variants opts in to cloning the donor's movie skins
        # (KentrosaurusCC, SpinosaurusJWR, VelociraptorBlue...). Lives on the
        # species config in the UI, but clone_fdb reads fdb_overrides.
        if "cosmetics" in sp_conf:
            fdb_ov["cosmetics"] = sp_conf["cosmetics"]
        dino_res = clone_fdb(
            source_fdb=src_dino_fdb,
            target_fdb=dst_dino_fdb,
            donor_species=sp_conf["source"],
            new_species=sp_conf["name"],
            new_species_id=sp_conf["species_id"],
            new_genetic_id=sp_conf["genetic_id"],
            donor_prefabs=sp_conf.get("donor_prefabs", {}),
            fdb_overrides=fdb_ov,
            report=report
        )

        resolved_members = dino_res.get("_resolved_members") if isinstance(dino_res, dict) else None
        plan["_resolved_members"] = resolved_members
        _invoke_fault(config, "dinosaur_clone")


        clone_expeditions_fdb(
            source_exp_fdb=src_exp_fdb,
            target_exp_fdb=dst_exp_fdb,
            donor_species=sp_conf["source"],
            new_species=sp_conf["name"],
            new_species_id=sp_conf["species_id"],
            new_genetic_id=sp_conf["genetic_id"],
            custom_digsite=bool(sp_conf.get("custom_digsite", False)),
            fdb_overrides=sp_conf.get("expeditions_overrides", {}),
            report=report,
            resolved_members=resolved_members
        )
        _invoke_fault(config, "expedition_clone")

    for fdb_path in (dst_dino_fdb, dst_exp_fdb):
        add_provenance_view(fdb_path)



    # Generate localizations across all 14 language subfolders
    for plan in plans:
        sp_conf = plan["config"]
        generate_species_localizations(out_dir, sp_conf["name"], report)

    # Rebuild each plan's cosmetic Lua stub list from the FDB rows clone_fdb
    # just committed, rather than the fixed-count guess plan_species made
    # before the FDB existed. Must happen after the clone loop above (so the
    # rows exist) and before write_scaffold (which is what writes the .lua
    # files) - see _cosmetic_plan_from_fdb for why.
    for plan in plans:
        real_plan = _cosmetic_plan_from_fdb(dst_dino_fdb, plan)
        if real_plan:
            plan["cosmetic_plan"] = real_plan
        elif plan.get("_resolved_members"):
            # resolved but the donor genuinely has 0 cosmetic sets - do not
            # keep the fixed-count guess in this case either, or a stub would
            # be written for a set that was never cloned.
            plan["cosmetic_plan"] = []

    written = write_scaffold(out_dir, mod_name, plans, config, report)
    _invoke_fault(config, "scaffolding")
    project_path = os.path.join(out_dir, "mod_project.json")
    persisted_config = {k: v for k, v in config.items() if not k.startswith("_")}
    with open(project_path, "w", encoding="utf-8") as stream:
        json.dump(persisted_config, stream, indent=2)
    return {
        "dinosaurs_fdb": dst_dino_fdb,
        "expeditions_fdb": dst_exp_fdb,
        "output_dir": out_dir,
        "project_file": project_path,
        "_written": written,
    }


def generate_species(mod_name, plans, report, config):
    """Preflight, stage, validate, and recoverably publish a generated mod."""
    validate_output_identifier(mod_name, "Mod project name")
    species_configs = config.get("species") or [p["config"] for p in plans]
    if not species_configs:
        raise ValueError("At least one species is required")
    seen_names = set()
    for index, sp_conf in enumerate(species_configs):
        name = validate_output_identifier(
            sp_conf.get("name"), f"Species #{index + 1} name")
        key = name.casefold()
        if key in seen_names:
            raise ValueError(f"Duplicate generated species name: {name!r}")
        seen_names.add(key)

    source_dino = config.get("source_dinosaurs_fdb") or os.path.join(
        BASE_DIR, "extracted_fdbs", "c0dinosaurs.fdb")
    source_exp = config.get("source_expeditions_fdb") or os.path.join(
        BASE_DIR, "extracted_fdbs", "c0expeditions.fdb")
    if not os.path.isfile(source_dino):
        raise FileNotFoundError(f"Source dinosaur FDB not found: {source_dino}")
    if not os.path.isfile(source_exp):
        raise FileNotFoundError(f"Source expeditions FDB not found: {source_exp}")
    output_root = config.get("_output_root") or os.path.join(BASE_DIR, "Generated")
    os.makedirs(output_root, exist_ok=True)
    reserved_sids, reserved_gids = _collect_generated_project_ids(
        output_root, mod_name)
    allocate_species_ids(
        species_configs, source_dino,
        reserved_species_ids=reserved_sids,
        reserved_genetic_ids=reserved_gids)
    con = sqlite3.connect(f"file:{source_dino}?mode=ro", uri=True)
    try:
        for sp_conf in species_configs:
            members = resolve_family_members(
                con, sp_conf["source"], sp_conf["name"], sp_conf["species_id"],
                donor_prefabs=sp_conf.get("donor_prefabs"),
                family_members=sp_conf.get("family_members"))
            for member in members:
                validate_output_identifier(
                    member["target_name"], "Generated family member name")
                validate_output_identifier(
                    member["target_prefab"], "Generated prefab name")
    finally:
        con.close()

    final_out = os.path.join(output_root, mod_name)
    _assert_tree_safe(final_out)
    config["uuid"] = _resolve_project_uuid(config, final_out)

    staging = tempfile.mkdtemp(prefix=".stg-", dir=output_root)
    backup = os.path.join(output_root, f".{mod_name}.backup-{uuid_mod.uuid4().hex}")
    old_moved = False
    had_original = os.path.isdir(final_out)
    published = False
    keep_staging = False
    try:
        if os.path.isdir(final_out):
            shutil.copytree(final_out, staging, dirs_exist_ok=True, copy_function=shutil.copy2)
        old_ownership = _load_ownership(staging)
        old_protected = _load_protected_files(staging)
        modified = _snapshot_modified_owned(
            staging, old_ownership, old_protected)
        paths = _build_species(staging, mod_name, plans, report, config)
        current_owned = _normalise_written_paths(staging, paths.pop("_written"))
        _reconcile_owned_files(staging, old_ownership, current_owned, modified, report)
        _validate_staging(
            staging, plans, paths["dinosaurs_fdb"], paths["expeditions_fdb"])
        _invoke_fault(config, "validation")

        _invoke_fault(config, "before_publish")
        if os.path.isdir(final_out):
            try:
                os.replace(final_out, backup)
            except OSError as move_exc:
                raise RuntimeError(
                    f"Cannot publish because the existing generated mod is locked or "
                    f"cannot be renamed. Close SQLite viewers and editor handles, then "
                    f"retry. The original is untouched at {final_out!r}: {move_exc}") from move_exc
            old_moved = True
        try:
            os.replace(staging, final_out)
            published = True
        except Exception as publish_exc:
            if old_moved:
                try:
                    os.replace(backup, final_out)
                    old_moved = False
                except Exception as rollback_exc:
                    keep_staging = True
                    raise RuntimeError(
                        f"Publishing failed and rollback also failed. Recovery copy remains at "
                        f"{backup!r}; staging remains at {staging!r}. Publish error: "
                        f"{publish_exc}; rollback error: {rollback_exc}") from publish_exc
            if had_original:
                message = "Publishing staged project failed; original was restored"
            else:
                message = "Publishing staged project failed before any existing project was moved"
            raise RuntimeError(f"{message}: {publish_exc}") from publish_exc

        if old_moved and os.path.isdir(backup):
            try:
                _safe_rmtree(backup, output_root)
            except Exception as cleanup_exc:
                report.setdefault("warnings", []).append(
                    f"Published successfully; old backup retained at {backup}: {cleanup_exc}")
        return {
            "dinosaurs_fdb": os.path.join(final_out, "Main", f"{mod_name.lower()}dinosaurs.fdb"),
            "expeditions_fdb": os.path.join(final_out, "Main", f"{mod_name.lower()}expeditions.fdb"),
            "output_dir": final_out,
            "project_file": os.path.join(final_out, "mod_project.json"),
        }
    finally:
        if not published and not keep_staging and os.path.isdir(staging):
            _safe_rmtree(staging, output_root)
